# @package _global_
defaults:
  - /model:
    - flat_enc_dec
    # - accel_tune
  - /model/task:
    - joint_bhvr_decode_flat
  - /train: pretrain
  - /dataset: flat
model:
  session_embed_token_count: 8
  subject_embed_strategy: EmbedStrat.token
  neurons_per_token: 16
  causal: true

  task:
    behavior_lag: 120
dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 1

  neurons_per_token: 16
  max_channels: 288

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel

  datasets:
  # - odoherty_rtt-Indy-20160624_03
  - odoherty_rtt-Indy.*
  eval_datasets:
  - odoherty_rtt-Indy-20161005_06
  # - odoherty_rtt-Indy-20160624_03

train:
  autoscale_batch_size: false
  batch_size: 32 # mind 12G nodes