# @package _global_

defaults:
  - m2
dataset:
  scale_ratio: 1.0
  falcon_m2:
    respect_trial_boundaries: False
    chop_size_ms: 2000
  augmentations: ['explicit_crop_time']
  augment_crop_length_ms: 1000
train:
  max_batch_size: 256
  batch_size: 64
effective_bsz: 128