# @package _global_
tag: maze_jenkins

defaults:
  - /model: pretrain
  - /dataset: maze
  - /train: pretrain

model:
  array_embed_strategy: EmbedStrat.token_add
dataset:
  datasets:
  - churchland_maze_jenkins.*
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  meta_keys:
  - MetaKey.unique
  - MetaKey.array
  - MetaKey.session