# @package _global_

tag: pitt_obs_20

defaults:
  - /model: pretrain
  - /train: nlb
dataset:
  datasets:
  - CRS02bHome.data.00329
  - CRS02bHome.data.00336
  - CRS02bHome.data.00339
  - CRS02bHome.data.00345
  - CRS02bHome.data.00360
  - CRS02bHome.data.00371
  - CRS02bHome.data.00402
  - CRS02bHome.data.00422
  - CRS02bHome.data.00424
  - CRS02bHome.data.00437
  - CRS02bHome.data.00445
  eval_datasets:
  - CRS02bHome.data.00445
  data_keys:
  - DataKey.spikes
  pitt_co:
    arrays:
    - CRS02b-lateral_m1
    - CRS02b-medial_m1
    - CRS02b-sensory
  max_length_ms: 4000
  max_arrays: 3
  bin_size_ms: 20
  max_channels: 96
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
model:
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
train:
  batch_size: 16
  accumulate_batches: 4
sweep_cfg: base