# @package _global_
defaults:
  - /model:
    - flat_enc_dec
    # - accel_tune
  - /model/task:
    - bhvr_decode_flat
  - /train: finetune
  - /dataset: flat
model:
  session_embed_token_count: 8
  subject_embed_strategy: EmbedStrat.token
  neurons_per_token: 16
  causal: true

  task:
    decode_separate: True
    behavior_lag: 120

    freeze_backbone: false
    freeze_all: false
dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 1

  neurons_per_token: 16
  max_channels: 288

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel

  datasets:
  - mc_rtt
  eval_datasets:
  - mc_rtt
  # Has ~1K trials, use 800 trials as a "super high regime" fine tuning and then TODO tweak scale ratio
  eval_ratio: 0.2
  scale_ratio: 0.1
train:
  patience: 600
# init_from_id: indy_causal_v2-3w1f6vzx
# init_tag: val_loss