# @package _global_
# Gunning for O'Doherty 0.57 R^2 with only 180 trials in day.
defaults:
  - /model: flat_enc_dec
  - /model/task:
    - bhvr_decode_flat
  - /train: finetune
  - /dataset: flat
model:
  subject_embed_strategy: EmbedStrat.token
  causal: true
  task:
    # mask_ratio: 0.5 # 0.25 may improve
    decode_separate: true
    behavior_lag: 120
  neurons_per_token: 8
dataset:
  neurons_per_token: 8
  max_tokens: 8192 # fit
  max_length_ms: 2000 # fit
  max_arrays: 1
  max_channels: 104

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel

  datasets:
  - odoherty_rtt-Indy.*
  eval_datasets:
  - odoherty_rtt-Indy-20161005_06
train:
  batch_size: 64