# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: flat
  - /train: single_session_exp1
model:
  # decoder_context_integration: 'cross_attn'
  causal: true
  subject_embed_strategy: EmbedStrat.token
  task:
    # decode_time_pool: ""
    mask_ratio: 0.5
  neurons_per_token: 32
dataset:
  datasets:
  - observation_.*
  - ortho_.*
  - fbc_.*
  - unstructured_.*
  - pitt_co.*
  # Our "test set"
  exclude_datasets:
  - observation_P2Lab_session_19.* #
  - observation_P3Lab_session_15.*
  - observation_P3Lab_session_16.*
  # There are at least 4 test sessions for P3 and 8 for P2Lab
train:
  autoscale_batch_size: false
  batch_size: 32
  accumulate_batches: 4
