# @package _global_

tag: maze_med_ft

defaults:
  - /model: finetune
  - /model/task: nlb
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze_medium
  nlb_maze:
    heldout_neurons: 38
    # small is 35, large is 40

init_from_id: "maze_med-6jk50oqx"
