# @package _global_
defaults:
  - /model: flat_enc_dec
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # array_embed_strategy: EmbedStrat.token_add
  # causal: True
  transformer:
    n_layers: 9

  task:
    mask_ratio: 0.5
    tasks:
    - ModelTask.shuffle_infill
    metrics: []
  neurons_per_token: 4
dataset:
  neurons_per_token: 4
  max_tokens: 4096 # full context
  max_arrays: 1
  bin_size_ms: 5
  serve_tokenized: true
  serve_tokenized_flat: true
  max_channels: 100
  # explicitly, the data here is Indy + Loco
  eval_datasets:
  - 'mc_rtt'
  # - 'odoherty_rtt-Indy-20161005_06'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
