# @package _global_
defaults:
  - /model:
    - flat_enc_dec
    # - accel_tune
  # - /model/task:
    # - bhvr_decode_flat
  # - /train: finetune
  - /dataset: flat
model:
  session_embed_token_count: 8
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 16

  task:
    behavior_lag: 120
    decode_time_pool: "mean"

  lr_init: 5e-5
  lr_ramp_steps: 1000
  lr_decay_steps: 10000
  accelerate_new_params: 10.0
  tune_decay: 0.75 # per Kaiming MAE

dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 2

  scale_limit_per_eval_session: 1600
  scale_limit_per_session: 0

  neurons_per_token: 16
  max_channels: 288

  data_keys:
  - DataKey.spikes
  # - DataKey.bhvr_vel
  datasets:
  # - mc_maze$
  # - dyer_co.*
  # - churchland_misc.*
  - odoherty_rtt-Indy-20160627_01

  eval_datasets:
  - odoherty_rtt-Indy-20160627_01

  churchland_misc:
    arrays: ["Reggie-M1", "Nitschke-M1", "Jenkins-M1"]
train:
  patience: 200
  # autoscale_batch_size: false
  # batch_size: 256
init_from_id: reach_80000-qp92sqlc
init_tag: val_loss