# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: flat
  - /train: single_session_exp1
model:
  # decoder_context_integration: 'cross_attn'
  causal: true
  subject_embed_strategy: EmbedStrat.token
  task:
    # decode_time_pool: ""
    mask_ratio: 0.5
  neurons_per_token: 32
dataset:
  datasets:
  - churchland_maze.*
  data_keys:
  - DataKey.spikes
  # - DataKey.bhvr_vel
train:
  # accumulate_batches: 2 # auto = 128 (12G GPUs), effective = 2048
  autoscale_batch_size: true
  # batch_size: 32
