# @package _global_
tag: rtt_maze_5_factor_2

defaults:
  - /model: pretrain_2x
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # token add not implemented for spacetime

  spike_embed_style: EmbedStrat.token
  neurons_per_token: 2
  hidden_size: 256
  transform_space: true
  transformer:
    factorized_space_time: true

  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
dataset:
  datasets:
  - odoherty_rtt-Indy.* # Note we're just using indy here.
  - mc_rtt
  - mc_maze.*
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1
  eval_datasets:
  - mc_rtt
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  bin_size_ms: 5

  max_channels: 138
  # max_channels: 98